- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS 
      debug: 
        msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
    - name: obtaining OS Version  
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
    
        