- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS version
      debug: "{{ item }}"
      with_items: 
        var: "{ hostvars[inventory_hostname].ansible_distribution }}"
        