- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS version
      shell: cat /etc/os-release
      register: result
    - name: print OS version
      debug: var=result.stdout