- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS version
      debug: 
         msg:
         - "ansible_distribution {{ hostvars[inventory_hostname].ansible_distribution }}"
         - "major version {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
         - "version {{ hostvars[inventory_hostname].ansible_distribution_version }}"
         - "ansible_all_ipv4_addresses"
 
    #- name: Get the IP
        
    
        