- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS version
      debug: 
        msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
    
        