- hosts: all
  become_user: ec2-user
  become_method: sudo
  tasks:
    - name: obtain OS version
      debug: "{{ item }}""
      with_items: 
        - msg: "{ hostvars[inventory_hostname].ansible_distribution }}"
        - msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"